In [145]:
import os
dataDir = "data"
filename = "fake.csv"
filepath = os.path.join(dataDir, filename)

# Load Data

In [153]:
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split

testingSplit = .2

data = pd.read_csv(filepath)
categorical = pd.get_dummies(data["label"].values).values
for i, row in data.iterrows():
    onehot = categorical[i]
    data.set_value(i, 'label', onehot)

data

Sequence Name   mcg   gvh   lip  chg   aac  alm1  alm2  \
0       AAT_ECOLI  0.49  0.29  0.48  0.5  0.56  0.24  0.35   
1      ACEA_ECOLI  0.07  0.40  0.48  0.5  0.54  0.35  0.44   
2      ACEK_ECOLI  0.56  0.40  0.48  0.5  0.49  0.37  0.46   
3      ACKA_ECOLI  0.59  0.49  0.48  0.5  0.52  0.45  0.36   
4       ADI_ECOLI  0.23  0.32  0.48  0.5  0.55  0.25  0.35   
5      ALKH_ECOLI  0.67  0.39  0.48  0.5  0.36  0.38  0.46   
6      AMPD_ECOLI  0.29  0.28  0.48  0.5  0.44  0.23  0.34   
7      AMY2_ECOLI  0.21  0.34  0.48  0.5  0.51  0.28  0.39   
8       APT_ECOLI  0.20  0.44  0.48  0.5  0.46  0.51  0.57   
9      ARAC_ECOLI  0.42  0.40  0.48  0.5  0.56  0.18  0.30   
10     ASG1_ECOLI  0.42  0.24  0.48  0.5  0.57  0.27  0.37   
11     BTUR_ECOLI  0.25  0.48  0.48  0.5  0.44  0.17  0.29   
12     CAFA_ECOLI  0.39  0.32  0.48  0.5  0.46  0.24  0.35   
13     CAIB_ECOLI  0.51  0.50  0.48  0.5  0.46  0.32  0.35   
14      CFA_ECOLI  0.22  0.43  0.48  0.5  0.48  0.16  0.28   
15     CHEA_ECOLI  0.25  0.40  0.48  0.5  0.46  0.44  0.52   
16     CHEB_ECOLI  0.34  0.45  0.48  0.5  0.38  0.24  0.35   
17     CHEW_ECOLI  0.44  0.27  0.48  0.5  0.55  0.52  0.58   
18     CHEY_ECOLI  0.23  0.40  0.48  0.5  0.39  0.28  0.38   
19     CHEZ_ECOLI  0.41  0.57  0.48  0.5  0.39  0.21  0.32   
20      CRL_ECOLI  0.40  0.45  0.48  0.5  0.38  0.22  0.00   
21     CSPA_ECOLI  0.31  0.23  0.48  0.5  0.73  0.05  0.14   
22     CYNR_ECOLI  0.51  0.54  0.48  0.5  0.41  0.34  0.43   
23     CYPB_ECOLI  0.30  0.16  0.48  0.5  0.56  0.11  0.23   
24     CYPC_ECOLI  0.36  0.39  0.48  0.5  0.48  0.22  0.23   
25     CYSB_ECOLI  0.29  0.37  0.48  0.5  0.48  0.44  0.52   
26     CYSE_ECOLI  0.25  0.40  0.48  0.5  0.47  0.33  0.42   
27     DAPD_ECOLI  0.21  0.51  0.48  0.5  0.50  0.32  0.41   
28      DCP_ECOLI  0.43  0.37  0.48  0.5  0.53  0.35  0.44   
29     DDLA_ECOLI  0.43  0.39  0.48  0.5  0.47  0.31  0.41   
..            ...   ...   ...   ...  ...   ...   ...   ...   
306    HTRA_ECOLI  0.63  0.71  0.48  0.5  0.60  0.40  0.39   
307    LIVJ_ECOLI  0.71  0.86  0.48  0.5  0.40  0.54  0.32   
308    LIVK_ECOLI  0.68  0.78  0.48  0.5  0.43  0.44  0.42   
309    MALE_ECOLI  0.64  0.84  0.48  0.5  0.37  0.45  0.40   
310    MALM_ECOLI  0.74  0.47  0.48  0.5  0.50  0.57  0.42   
311    MEPA_ECOLI  0.75  0.84  0.48  0.5  0.35  0.52  0.33   
312    MODA_ECOLI  0.63  0.65  0.48  0.5  0.39  0.44  0.35   
313    NRFA_ECOLI  0.69  0.67  0.48  0.5  0.30  0.39  0.24   
314    NRFF_ECOLI  0.70  0.71  0.48  0.5  0.42  0.84  0.85   
315    OPPA_ECOLI  0.69  0.80  0.48  0.5  0.46  0.57  0.26   
316    OSMY_ECOLI  0.64  0.66  0.48  0.5  0.41  0.39  0.20   
317    POTD_ECOLI  0.63  0.80  0.48  0.5  0.46  0.31  0.29   
318    POTF_ECOLI  0.66  0.71  0.48  0.5  0.41  0.50  0.35   
319     PPA_ECOLI  0.69  0.59  0.48  0.5  0.46  0.44  0.52   
320     PPB_ECOLI  0.68  0.67  0.48  0.5  0.49  0.40  0.34   
321    PROX_ECOLI  0.64  0.78  0.48  0.5  0.50  0.36  0.38   
322    PSTS_ECOLI  0.62  0.78  0.48  0.5  0.47  0.49  0.54   
323     PTR_ECOLI  0.76  0.73  0.48  0.5  0.44  0.39  0.39   
324    RBSB_ECOLI  0.64  0.81  0.48  0.5  0.37  0.39  0.44   
325    SPEA_ECOLI  0.29  0.39  0.48  0.5  0.52  0.40  0.48   
326    SUBI_ECOLI  0.62  0.83  0.48  0.5  0.46  0.36  0.40   
327    TBPA_ECOLI  0.56  0.54  0.48  0.5  0.43  0.37  0.30   
328    TESA_ECOLI  0.69  0.66  0.48  0.5  0.41  0.50  0.25   
329    TOLB_ECOLI  0.69  0.65  0.48  0.5  0.63  0.48  0.41   
330    TORA_ECOLI  0.43  0.59  0.48  0.5  0.52  0.49  0.56   
331    TREA_ECOLI  0.74  0.56  0.48  0.5  0.47  0.68  0.30   
332    UGPB_ECOLI  0.71  0.57  0.48  0.5  0.48  0.35  0.32   
333    USHA_ECOLI  0.61  0.60  0.48  0.5  0.44  0.39  0.38   
334    XYLF_ECOLI  0.59  0.61  0.48  0.5  0.42  0.42  0.37   
335    YTFQ_ECOLI  0.74  0.74  0.48  0.5  0.31  0.53  0.52   

                                                 label  
0    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
1    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

# Data Prep

In [147]:
data.columns
data = data.drop('Sequence Name', 1)

train, validation = train_test_split(data, test_size=testingSplit)
trainX, trainY = train[train.columns[:-1]], train["label"]
testX, testY = validation[validation.columns[:-1]], validation["label"]
trainX

mcg   gvh   lip  chg   aac  alm1  alm2
265  0.73  0.84  0.48  0.5  0.86  0.58  0.29
203  0.35  0.51  0.48  0.5  0.61  0.71  0.74
333  0.61  0.60  0.48  0.5  0.44  0.39  0.38
19   0.41  0.57  0.48  0.5  0.39  0.21  0.32
18   0.23  0.40  0.48  0.5  0.39  0.28  0.38
59   0.42  0.38  0.48  0.5  0.54  0.34  0.43
186  0.89  0.55  0.48  0.5  0.51  0.72  0.76
114  0.38  0.44  0.48  0.5  0.43  0.20  0.31
123  0.04  0.31  0.48  0.5  0.41  0.29  0.39
282  0.67  0.55  1.00  0.5  0.66  0.58  0.10
275  0.69  0.59  0.48  0.5  0.77  0.39  0.21
187  0.70  0.46  0.48  0.5  0.56  0.78  0.73
277  0.71  0.71  0.48  0.5  0.68  0.43  0.36
68   0.25  0.37  0.48  0.5  0.43  0.26  0.36
116  0.34  0.42  0.48  0.5  0.41  0.34  0.43
14   0.22  0.43  0.48  0.5  0.48  0.16  0.28
117  0.51  0.49  0.48  0.5  0.53  0.14  0.26
238  0.81  0.44  0.48  0.5  0.42  0.67  0.60
279  0.77  0.57  1.00  0.5  0.37  0.54  0.00
227  0.69  0.43  0.48  0.5  0.59  0.74  0.70
7    0.21  0.34  0.48  0.5  0.51  0.28  0.39
222  0.75  0.55  1.00  1.0  0.40  0.47  0.30
228  0.79  0.36  0.48  0.5  0.46  0.82  0.70
263  0.67  0.84  0.48  0.5  0.74  0.54  0.37
161  0.50  0.66  0.48  0.5  0.31  0.92  0.92
258  0.78  0.44  0.48  0.5  0.45  0.73  0.60
21   0.31  0.23  0.48  0.5  0.73  0.05  0.14
130  0.00  0.38  0.48  0.5  0.42  0.48  0.55
31   0.34  0.33  0.48  0.5  0.38  0.35  0.44
120  0.25  0.26  0.48  0.5  0.39  0.32  0.42
..    ...   ...   ...  ...   ...   ...   ...
327  0.56  0.54  0.48  0.5  0.43  0.37  0.30
157  0.84  0.44  0.48  0.5  0.48  0.71  0.74
101  0.24  0.57  0.48  0.5  0.63  0.34  0.43
127  0.40  0.46  0.48  0.5  0.42  0.35  0.44
131  0.39  0.31  0.48  0.5  0.38  0.34  0.43
133  0.27  0.30  0.48  0.5  0.71  0.28  0.39
190  0.33  0.37  0.48  0.5  0.46  0.65  0.69
16   0.34  0.45  0.48  0.5  0.38  0.24  0.35
270  0.56  0.68  0.48  0.5  0.77  0.36  0.45
28   0.43  0.37  0.48  0.5  0.53  0.35  0.44
5    0.67  0.39  0.48  0.5  0.36  0.38  0.46
281  0.71  0.46  1.00  0.5  0.52  0.59  0.30
192  0.41  0.51  0.48  0.5  0.53  0.75  0.78
296  0.66  0.74  0.48  0.5  0.31  0.38  0.43
48   0.42  0.35  0.48  0.5  0.58  0.15  0.27
85   0.40  0.46  0.48  0.5  0.52  0.49  0.56
132  0.30  0.44  0.48  0.5  0.49  0.22  0.33
301  0.70  0.64  0.48  0.5  0.47  0.51  0.47
163  0.47  0.55  0.48  0.5  0.58  0.71  0.75
303  0.74  0.82  0.48  0.5  0.49  0.49  0.41
245  0.47  0.46  0.48  0.5  0.62  0.74  0.70
124  0.61  0.36  0.48  0.5  0.49  0.35  0.44
188  0.12  0.43  0.48  0.5  0.63  0.70  0.74
65   0.24  0.43  0.48  0.5  0.54  0.52  0.59
158  0.48  0.45  0.48  0.5  0.60  0.78  0.80
300  0.32  0.39  0.48  0.5  0.53  0.28  0.38
237  0.77  0.55  0.48  0.5  0.51  0.78  0.70
205  0.61  0.66  0.48  0.5  0.46  0.87  0.88
221  0.63  0.49  0.48  0.5  0.54  0.76  0.70
332  0.71  0.57  0.48  0.5  0.48  0.35  0.32

[268 rows x 7 columns]

In [148]:
trainY.values

array([ array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0], dtype=uint8),
       array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0], dtype=uint8),
       array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], dtype=uint8),
       array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0], dtype=uint8),
       array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0], dtype=uint8),
       array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0], dtype=uint8),
       array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0], dtype=uint8),
       array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0], dtype=uint8),
       array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0], dtype=uint8),
       array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint8),
       array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

# Dimensionality Reduction

In [149]:
pca = PCA(n_components=2)
reducedX = pca.fit_transform(trainX)
reducedTestX = pca.fit_transform(testX)

In [150]:
reducedX

array([[  9.16183846e-02,   4.37766694e-01],
       [  2.58410779e-01,  -2.25353726e-01],
       [ -1.10562991e-01,   1.79298219e-01],
       [ -3.51140125e-01,   5.16894188e-02],
       [ -3.42267346e-01,  -1.96624806e-01],
       [ -1.86317003e-01,  -8.41320509e-02],
       [  4.49875696e-01,   1.77884364e-01],
       [ -3.80548985e-01,  -2.83497642e-02],
       [ -3.98956428e-01,  -3.85607813e-01],
       [ -8.41416189e-02,   3.69998851e-01],
       [ -1.39464422e-01,   3.25146262e-01],
       [  4.08844507e-01,   4.81993957e-03],
       [ -1.65351144e-02,   3.27169432e-01],
       [ -3.58674858e-01,  -1.84770987e-01],
       [ -2.28089438e-01,  -1.30055545e-01],
       [ -4.74800020e-01,  -1.32976726e-01],
       [ -3.90152195e-01,   1.23437910e-01],
       [  2.69125756e-01,   1.31961279e-01],
       [ -1.77346911e-01,   4.84241658e-01],
       [  3.60757206e-01,  -3.53230996e-04],
       [ -3.31619524e-01,  -2.39305794e-01],
       [ -5.24955627e-02,   3.41789096e-01],
       [  

# Decision Tree

In [151]:
from sklearn import tree
def decisionTree(trainX, trainY, validX, validY):
    clf = tree.DecisionTreeClassifier()
    clf = clf.fit(reducedX, trainY)
    prediction = clf.predict(validX)
    zOneLoss = (validY - prediction).apply(lambda x: 0 if x is 0 else 1)
    score = 1 - zOneLoss.sum()/len(zOneLoss)
    print(score)

print("Before Reduction")
decisionTree(trainX, trainY, reducedTestX, testY)
print("With Reduction")
decisionTree(reducedX, trainY, reducedTestX, testY)

Before Reduction


ValueError: Unknown label type: 'unknown'

# Logistic Regression

In [152]:
from sklearn import linear_model
def logReg(trainX, trainY, validX, validY, regularizer_coefficient=None):
    if regularizer_coefficient is not None:
        lr = linear_model.LogisticRegression(C=regularizer_coefficient)
    else:
        lr = linear_model.LogisticRegression()
    lr.fit(trainX, trainY)
    print(lr.score(validX, validY))

print("Before Reduction")
logReg(trainX, trainY, reducedTestX, testY)
print("With Reduction")
logReg(reducedX, trainY, reducedTestX, testY)

Before Reduction


ValueError: Unknown label type: 'unknown'

# K Nearest Neighbors

In [78]:
from sklearn import neighbors
def kNN(trainX, trainY, validX, validY, num_neighbors=3):
    nn = neighbors.KNeighborsClassifier(num_neighbors)
    nn.fit(trainX, trainY)
    print(nn.score(validX, validY))

print("Before Reduction")
kNN(trainX, trainY, testX, testY)

print("With Reduction")
kNN(reducedX, trainY, reducedTestX, testY)

0.867647058824
0.720588235294


# SVM

In [79]:
from sklearn.svm import SVC
def svm(trainX, trainY, validX, validY, regularizer_coefficient=None):
    if regularizer_coefficient is not None:
        lr = SVC(C=regularizer_coefficient)
    else:
        lr = SVC()
    lr.fit(trainX, trainY)
    print(lr.score(validX, validY))

print("Before Reduction")
svm(trainX, trainY, testX, testY)

print("Without Reduction")
svm(reducedX, trainY, reducedTestX, testY)

Before Reduction
0.838235294118
Without Reduction
0.794117647059
