In [1]:
import os
dataDir = "data"
filename = "fake.csv"
filepath = os.path.join(dataDir, filename)

# Load Data

In [113]:
import numpy as np
import pandas as pd
from sklearn.decomposition import PCA
# from sklearn.model_selection import train_test_split
import sklearn
testingSplit = .2

data = pd.read_csv(filepath)
# categorical = pd.get_dummies(data["label"].values).values
# for i, row in data.iterrows():
#     onehot = categorical[i]
#     data.set_value(i, 'label', onehot)

# data["label"].apply(lambda x: list(x))

data = data.reindex(np.random.permutation(data.index))

# Data Prep

In [114]:
data = data.drop('Sequence Name', 1)

In [115]:
train, validation = data[:int(len(data)*0.8)], data[int(len(data)*0.8):]
trainX, trainY = train[train.columns[:-1]], train["label"]
testX, testY = validation[validation.columns[:-1]], validation["label"]
trainX
testY.values

tlist = []
for i in range(len(trainY.values)):
    tlist.append(trainY.values[i])
trainY = np.array(tlist)

tlist = []
for i in range(len(testY.values)):
    tlist.append(testY.values[i])
testY = np.array(tlist)

combined = np.concatenate((trainY, testY), axis=0)


from sklearn import preprocessing
encoder = preprocessing.LabelEncoder()
encoder.fit(combined)
trainY = encoder.transform(trainY)
testY = encoder.transform(testY)

In [117]:
trainY

array([18, 18, 21, 18, 18, 19, 18, 19,  4, 19, 17, 21, 19,  8, 18,  0, 19,
       18, 20, 21, 19, 18, 18,  8, 18, 19, 20, 19, 19, 18, 19, 18, 20, 18,
       18, 20, 18, 18, 19, 20, 19, 18, 18, 18,  1, 18, 18, 21, 21, 18, 21,
       18, 19, 14,  1, 20, 14, 18, 18, 18, 21, 19, 12, 19, 18, 21, 18, 18,
       20, 18, 18, 20, 21, 18, 21, 18, 21,  3, 19, 19, 19, 21, 19, 16, 21,
       11, 18,  6, 18, 10, 18, 18, 12, 19, 18, 18, 19, 18, 18, 14, 21, 18,
       18, 21,  5, 19, 19, 18, 18, 21, 21, 18, 21, 20, 19, 18, 19, 18, 20,
       18, 20, 18, 21, 19, 11, 17, 18, 21, 14, 19, 18, 18, 19, 18, 18, 19,
       19, 19, 18, 18, 18, 18, 21, 21, 19, 21, 21,  1,  2, 21, 18, 19, 18,
       19, 18, 20, 18, 19,  1, 14, 18, 19, 18, 18, 19, 21, 20, 18, 18, 18,
       20,  6, 18, 21, 17, 18, 18, 18, 21, 18, 21, 21, 18, 18, 18, 19, 18,
       19, 15, 18, 18, 21, 19, 18, 18, 19, 18, 20, 18, 13, 13, 19, 18, 18,
       19, 13, 10, 19,  6, 21, 19, 18, 11, 18, 19, 18, 18, 18, 18, 19,  7,
       20, 19, 17, 18, 19

# Dimensionality Reduction

In [75]:
pca = PCA(n_components=2)
reducedX = pca.fit_transform(trainX)
reducedTestX = pca.fit_transform(testX)

In [76]:
reducedX

array([[  2.90221178e-01,   1.26954914e-01],
       [  3.09150645e-01,  -2.77028633e-01],
       [  1.07417558e-01,   1.30234141e-01],
       [  8.21186826e-02,   1.97354697e-01],
       [  3.78810192e-01,  -9.65500480e-02],
       [  8.04838187e-02,   2.04759875e-01],
       [  3.97892987e-01,  -5.83341960e-02],
       [  3.46154394e-01,  -1.36803091e-01],
       [  8.12650487e-02,  -2.50784608e-01],
       [  3.74051456e-01,   1.19724790e-01],
       [  2.88455422e-01,   4.34993715e-02],
       [  4.59671685e-01,  -2.18691603e-02],
       [  3.39698334e-01,   3.30047107e-02],
       [  2.17046090e-01,   1.54711409e-01],
       [  4.83466109e-01,  -4.65834784e-02],
       [  1.45012242e-01,  -1.80935636e-01],
       [  3.55310957e-01,   4.67467953e-03],
       [ -1.51991206e-02,  -6.99035497e-02],
       [  3.55820949e-01,  -1.19488810e-01],
       [  3.51326105e-01,   1.08171754e-01],
       [  5.47778805e-01,   1.91949705e-01],
       [  5.92259203e-01,   1.01571644e-01],
       [  

# Decision Tree

In [107]:
from sklearn import tree
def decisionTree(trainX, trainY, validX, validY):
    clf = tree.DecisionTreeClassifier()
    clf = clf.fit(reducedX, trainY)
    prediction = clf.predict(validX)
    zOneLoss = (validY - prediction).apply(lambda x: 0 if x is 0 else 1)
    score = 1 - zOneLoss.sum()/len(zOneLoss)
    print(score)

print("Before Reduction")
decisionTree(trainX, trainY, reducedTestX, testY)
print("With Reduction")
decisionTree(reducedX, trainY, reducedTestX, testY)

Before Reduction


AttributeError: 'numpy.ndarray' object has no attribute 'apply'

In [41]:
testY.values

array([ array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.]),
       array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.]),
       array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.]),
       array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.]),
       array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.]),
       array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.]),
       array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.]),
       array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,

# Logistic Regression

In [118]:
from sklearn import linear_model
def logReg(trainX, trainY, validX, validY, regularizer_coefficient=None):
    if regularizer_coefficient is not None:
        lr = linear_model.LogisticRegression(C=regularizer_coefficient)
    else:
        lr = linear_model.LogisticRegression()
    lr.fit(trainX, trainY)
    print(lr.score(validX, validY))

    
print("Before Reduction")
logReg(trainX, trainY, testX, testY)
print("With Reduction")
logReg(reducedX, trainY, reducedTestX, testY)


Before Reduction
0.75
With Reduction
0.470588235294


# K Nearest Neighbors

In [119]:
from sklearn import neighbors
def kNN(trainX, trainY, validX, validY, num_neighbors=3):
    nn = neighbors.KNeighborsClassifier(num_neighbors)
    nn.fit(trainX, trainY)
    print(nn.score(validX, validY))

print("Before Reduction")
kNN(trainX, trainY, testX, testY)

print("With Reduction")
kNN(reducedX, trainY, reducedTestX, testY)

Before Reduction
0.823529411765
With Reduction
0.264705882353


# SVM

In [120]:
from sklearn.svm import SVC
def svm(trainX, trainY, validX, validY, regularizer_coefficient=None):
    if regularizer_coefficient is not None:
        lr = SVC(C=regularizer_coefficient)
    else:
        lr = SVC()
    lr.fit(trainX, trainY)
    print(lr.score(validX, validY))

print("Before Reduction")
svm(trainX, trainY, testX, testY)

print("Without Reduction")
svm(reducedX, trainY, reducedTestX, testY)

Before Reduction
0.779411764706
Without Reduction
0.470588235294
